#! /usr/bin/env python
################################################################################################################################################
# Select a video to interactively tag by adding chapters
# A chapter will consist of continuous action (hereby referred to as a sequence) and will end when the action stops
################################################################################################################################################
# Chapters are made up of 5 main pieces of data:
# - Time: The timestamps (from the video not the match) of the start and end of a sequence
# - Attacker: Was your wrestler the one who made the first committed attack
# - Tie-up/Position: What was the position or tie-up that the sequence began in
# - Moves: What moves did each wrestler use
# - Scoring: How many points did each wrestler score and how
################################################################################################################################################

import subprocess
from helpers import *

def VideoSelect() -> str:
    return subprocess.run(
        "ls ./vids/untaged/ | fzf --header='Select the Video You Want to Tag\n"
            "WARNING: This file will be deleted and a new one will be created in the taged folder' "
            "--header-border=bold --header-label-pos=top --no-multi",
        shell=True,
        capture_output=True,
        text=True,
        check=True  # Raises a CalledProcessError if the command returns a non-zero exit code
    ).stdout

def AskToContinue() -> bool:
    return subprocess.run(
        "echo 'New Sequence\nDone' | fzf --header='Do you have new sequences to add?' "
            "--header-border=bold --header-label-pos=top --no-multi",
        shell=True,
        capture_output=True,
        text=True,
        check=True  # Raises a CalledProcessError if the command returns a non-zero exit code
    ).stdout.removesuffix("\n") == 'New Sequence'

    

vid_file_name : str = VideoSelect()

wrestler_name : str = SelectFromConfig("Wrestlers.config",
                                       "Select the wrestler from your team.")

chap_list : [Chapter] = list()

new_chap : bool = True
while(new_chap):
    start : int = GetTime("Enter the START time in this format mins:secs\t")

    attacking : bool = "Attacking" == subprocess.run(
        "echo 'Attacking\nDefending' | fzf --header='Was YOUR wrestler initially attacking or defending?' "
            "--header-border=bold --header-label-pos=top --no-multi",
        shell=True,
        capture_output=True,
        text=True,
        check=True  # Raises a CalledProcessError if the command returns a non-zero exit code
    ).stdout

    tie : str = SelectFromConfig("Ties.config", 
                                 "What was the inital position/tie-up?\nFrom The Perspective of YOUR wrestler.").removesuffix("\n")

    our_moves : [str] = SelectMultiFromConfig(
        "Moves.config",
        "Select the moves YOUR wrestler used in the sequence.\n"
            "Use tab to select multiple moves."
    ).removesuffix("\n").split(sep="\n") # Allows for move names to be multiple words

    other_moves : [str]   = SelectMultiFromConfig(
        "Moves.config",
        "Select the moves the OPPONENT used in the sequence.\n"
            "Use tab to select multiple moves."
    ).removesuffix("\n").split(sep="\n")

    our_seq : [str] = SelectMultiFromConfig(
        "Outcomes.config", 
        "What points did YOUR wrestler score?").removesuffix("\n").split(sep="\n")

    other_seq : [str] = SelectMultiFromConfig(
        "Outcomes.config", 
        "What points did the OPPONENT score?").removesuffix("\n").split(sep="\n")

    end : int = GetTime("Enter the END time in this format mins:secs\t")

    chap_list.append(Chapter(start_time=start,
                             end_time=end, 
                             attack_defend=attacking, 
                             tie_up=tie, 
                             team_moves=our_moves, 
                             op_moves=other_moves, 
                             team_scores=our_seq, 
                             op_scores=other_seq))

    new_chap = AskToContinue()



for chap in chap_list:
    print(chap)
    print(chap.ToMetadata())



