#! /usr/bin/env python
########################################################################
# Select a video to interactively tag by adding chapters
########################################################################
import subprocess
from helpers import *

def VideoSelect() -> str:
    return subprocess.run(
        "ls ./vids/untaged/ | fzf --header='Select the Video You Want to Tag\n"
            "WARNING: This file will be deleted and a new one will be created in the taged folder' "
            "--header-border=bold --header-label-pos=top --no-multi",
        shell=True,
        capture_output=True,
        text=True,
        check=True  # Raises a CalledProcessError if the command returns a non-zero exit code
    ).stdout

def AskForMore() -> str:
    return subprocess.run(
        "echo 'New Sequence\nDone' | fzf --header='Do you have new sequences to add?' "
            "--header-border=bold --header-label-pos=top --no-multi",
        shell=True,
        capture_output=True,
        text=True,
        check=True  # Raises a CalledProcessError if the command returns a non-zero exit code
    ).stdout

    

vid_in_path : str = f"./vids/untaged/{VideoSelect()}"

wrestler_name : str = SelectFromConfig("Wrestlers.config",
                                  "Select the wrestler from your team.")

chap_list : [Chapter] = list()

new_chap : bool = True
while(new_chap):
    start : int = GetTime("Enter the START time in this format mins:secs\t")

    attacking : bool = "Attacking" == subprocess.run(
        "echo 'Attacking\nDefending' | fzf --header='Was YOUR wresler initially attacking or defending?' "
            "--header-border=bold --header-label-pos=top --no-multi",
        shell=True,
        capture_output=True,
        text=True,
        check=True  # Raises a CalledProcessError if the command returns a non-zero exit code
    ).stdout

    our_moves : [str] = SelectMultiFromConfig(
        "Moves.config",
        "Select the moves YOUR wrestler used in the sequence.\n"
            "Use tab to select multiple moves."
    ).removesuffix("\n").split(sep="\n") # Allows for move names to be multiple words

    other_moves : [str]   = SelectMultiFromConfig(
        "Moves.config",
        "Select the moves the OPPOSING wrestler used in the sequence.\n"
            "Use tab to select multiple moves."
    ).removesuffix("\n").split(sep="\n")

    our_seq : [str] = SelectMultiFromConfig("Outcomes.config", "What points did YOUR wrestler score?").removesuffix("\n").split(sep="\n")

    other_seq : [str] = SelectMultiFromConfig("Outcomes.config", "What points did YOUR wrestler score?").removesuffix("\n").split(sep="\n")

    tie : str = SelectFromConfig("Ties.config", "What was the inital tie-up?").removesuffix("\n")

    end : int = GetTime("Enter the END time in this format mins:secs\t")

    chap_list.append(Chapter(start_time=start,
                             end_time=end, 
                             attack_defend=attacking, 
                             tie_up=tie, 
                             team_moves=our_moves, 
                             op_moves=other_moves, 
                             team_scores=our_seq, 
                             op_scores=other_seq))

    new_chap = "New Sequence" == AskForMore()



for chap in chap_list:
    print(chap)

 #print(vid_path, wrestler, "\n\n")
 #print(team_moves, "\n\n")
 #print(op_moves)


